# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  mandrill_username: Your_Username
  mandrill_apikey: Your_API_Key
  secret_key_base: e0e68cff434e55be1780bcebe9a834555d425f15d3c2ea44b0dbd262f802d9a470271fa71ee35b22822c89b5105edce9cb9bbc6c7976c2e98c6879725ae263a8

test:
  secret_key_base: fb2f2e35a6256e111968e62c67e822d05091cc71709de1f5a9a3fa24491a7cc15744431c79b811e738039285fbba3b36e7fda593fd06c28b9032ebda106dd8e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
